apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc-high-iops
annotations:
  storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: io1
  iopsPerGB: "200"
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - us-east-1b