apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc-ssd
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: pd-ssd
allowedTopologies:
- matchLabelExpressions:
  - key: topology.gke.io/zone
    values:
    - asia-east1-a